# Generated by Django 5.1.1 on 2024-11-24 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('StudentID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Semester', models.CharField(max_length=20)),
                ('Program', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('TeacherID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('TeacherName', models.CharField(max_length=100)),
                ('TeacherEmail', models.EmailField(max_length=100)),
                ('TeacherPassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=50)),
                ('Date', models.DateField()),
                ('check_in', models.TimeField(blank=True)),
                ('check_out', models.TimeField(blank=True)),
                ('status', models.CharField(blank=True, choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Leave')], max_length=10)),
                ('StudentID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.students')),
            ],
        ),
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=100)),
                ('Semester', models.CharField(max_length=100)),
                ('Program', models.CharField(max_length=100)),
                ('TeacherName', models.CharField(max_length=100)),
                ('ApplicationContent', models.TextField()),
                ('Date', models.DateField()),
                ('status', models.CharField(default='Pending', max_length=10)),
                ('StudentID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.students')),
                ('TeacherID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.teacher')),
            ],
        ),
    ]
